apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp
    tier: frontend
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoapp
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: demoapp
        tier: frontend
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
            name: http
status: {}
