apiVersion: v1
kind: Service
metadata:
  labels:
    app: demoapp
    tier: frontend
  name: nginx-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: demoapp
    tier: frontend
  type: NodePort